export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as RequestPassword } from './RequestPassword'
export { default as ResetPassword } from './ResetPassword'
export { default as Verification } from './Verification'
export { default as Login} from './Login'