export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as RequestPassword } from './RequestPassword'
export { default as ResetPassword } from './ResetPassword'
export { default as Verification } from './Verification'
export { default as Login} from './Login'
export {default as Dashboard} from './Dashboard'
export {default as AdminLogin} from './AdminLogin'
export {default as Warehouse} from './Warehouse'
export {default as UserManagement} from './UserManagement'
export {default as PageNotFound} from './PageNotFound'
export {default as CustomerProfile} from './CustomerProfile'
export {default as EditProfile} from './EditProfile'